# Stage 1: Build the UI
FROM node:20 AS ui-builder
WORKDIR /app
# Copy package.json and yarn.lock
COPY package.json yarn.lock ./
# Install frontend dependencies
RUN yarn install --frozen-lockfile
# Copy the ui folder
COPY ui/ ./ui/
# Build the frontend
RUN yarn build

# Stage 2: Build the Go binary
FROM golang:1.25 AS go-builder
WORKDIR /app
# Copy go.mod and go.sum
COPY go.mod go.sum ./
# Download Go dependencies
RUN go mod download
# Copy the rest of the project
COPY . .
# Copy the built UI from Stage 1 into the right place for embedding
COPY --from=ui-builder /app/ui/dist ./ui/dist
# Build the binary
RUN CGO_ENABLED=1 go build -o xbvr main.go

# Stage 3: Final image
FROM ubuntu:22.04
RUN apt-get update && \
    apt-get install -y --no-install-recommends python3 ca-certificates && \
    rm -rf /var/lib/apt/lists/*

COPY --from=go-builder /app/xbvr /usr/bin/xbvr
# place data next to the executable like other platforms
COPY xbvr_data/ /usr/bin/xbvr_data/
COPY docker_start.sh /
RUN chmod 777 /docker_start.sh

EXPOSE 9998-9999
VOLUME /root/.config/

CMD ["/usr/bin/xbvr"]
